version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple

    debug_file_handler:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: logs/debug.log
        encoding: utf8

root:
    level: DEBUG
    handlers: [console, debug_file_handler]